# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: npm audit

on:
  push:
    branches:
      - 'master'
      - 'npm-audit'

jobs:
  audit-root:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: npm audit (root)
      run: npm audit

  audit-lib:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          library:
            - msal-core
            - msal-common
            - msal-browser
            - msal-node
            - msal-angular
            - msal-angularjs
            - msal-react
  
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: npm audit (lib)
      working-directory: lib/${{ matrix.library }}
      run: npm audit
